//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5456
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.5456 版自动生成。
// 
namespace HISPlus.UserWebSrv {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserWebSrvSoap", Namespace="http://tempuri.org/")]
    public partial class UserWebSrv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public UserWebSrv() {
            this.Url = "http://localhost/MobileWebSrv/UserWebSrv.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSysDate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.DateTime GetSysDate() {
            object[] results = this.Invoke("GetSysDate", new object[0]);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetSysDate(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetSysDate", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public System.DateTime EndGetSysDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.DateTime)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkOracleUserPwd_Db", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChkOracleUserPwd_Db(string userId, string pwd) {
            object[] results = this.Invoke("ChkOracleUserPwd_Db", new object[] {
                        userId,
                        pwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChkOracleUserPwd_Db(string userId, string pwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChkOracleUserPwd_Db", new object[] {
                        userId,
                        pwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndChkOracleUserPwd_Db(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkOracleUserPwd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChkOracleUserPwd(string userId, string pwd) {
            object[] results = this.Invoke("ChkOracleUserPwd", new object[] {
                        userId,
                        pwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChkOracleUserPwd(string userId, string pwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChkOracleUserPwd", new object[] {
                        userId,
                        pwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndChkOracleUserPwd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangePwd_Db", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangePwd_Db(string userId, string newPwd) {
            object[] results = this.Invoke("ChangePwd_Db", new object[] {
                        userId,
                        newPwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChangePwd_Db(string userId, string newPwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChangePwd_Db", new object[] {
                        userId,
                        newPwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndChangePwd_Db(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChangePwd", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangePwd(string userId, string newPwd) {
            object[] results = this.Invoke("ChangePwd", new object[] {
                        userId,
                        newPwd});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChangePwd(string userId, string newPwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChangePwd", new object[] {
                        userId,
                        newPwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndChangePwd(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUserInfo(string userName, string pwd) {
            object[] results = this.Invoke("GetUserInfo", new object[] {
                        userName,
                        pwd});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetUserInfo(string userName, string pwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetUserInfo", new object[] {
                        userName,
                        pwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public System.Data.DataSet EndGetUserInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
    }
}
