select SERIAL_NO,
       DEPT_CODE,
       DEPT_NAME,
       DEPT_ALIAS,
       CLINIC_ATTR,
       OUTP_OR_INP,
       INTERNAL_OR_SERGERY,
       INPUT_CODE,POSITION,
       SIGN,
       INPUT_CODE_WB,
       DISPENSING_CUMULATE,
       VIRTUAL_CABINET  from dept_dict