SELECT PAT_MASTER_INDEX.PATIENT_ID,
       PAT_VISIT.VISIT_ID,
       PAT_MASTER_INDEX.INP_NO,
       PAT_MASTER_INDEX.NAME,
       PAT_MASTER_INDEX.SEX,
       PAT_MASTER_INDEX.DATE_OF_BIRTH + 1 / 24 DATE_OF_BIRTH,
       PAT_VISIT.ADMISSION_DATE_TIME,
       PATS_IN_HOSPITAL.ADM_WARD_DATE_TIME,
       PATS_IN_HOSPITAL.WARD_CODE,
       PATS_IN_HOSPITAL.DEPT_CODE,
       PAT_MASTER_INDEX.ID_NO,
       (SELECT DEPT_NAME FROM DEPT_DICT WHERE DEPT_CODE = PATS_IN_HOSPITAL.WARD_CODE) WARD_NAME,  
       (SELECT DEPT_NAME FROM DEPT_DICT WHERE DEPT_CODE = PATS_IN_HOSPITAL.DEPT_CODE) DEPT_NAME,
       PATS_IN_HOSPITAL.BED_NO,
       (SELECT BED_REC.BED_LABEL FROM BED_REC 
            WHERE BED_REC.BED_NO = PATS_IN_HOSPITAL.BED_NO 
            AND BED_REC.WARD_CODE = PATS_IN_HOSPITAL.WARD_CODE) BED_LABEL,
       (SELECT BED_REC.ROOM_NO FROM BED_REC 
            WHERE BED_REC.BED_NO = PATS_IN_HOSPITAL.BED_NO 
            AND BED_REC.WARD_CODE = PATS_IN_HOSPITAL.WARD_CODE) ROOM_NO,
       PATS_IN_HOSPITAL.DOCTOR_IN_CHARGE,
       PATS_IN_HOSPITAL.DIAGNOSIS,
       (SELECT ALERGY_DRUGS
          FROM PAT_VISIT
         WHERE PATIENT_ID = PATS_IN_HOSPITAL.PATIENT_ID AND
               VISIT_ID = PATS_IN_HOSPITAL.VISIT_ID) ALERGY_DRUGS,
       (SELECT PATIENT_STATUS_NAME
          FROM PATIENT_STATUS_DICT
         WHERE PATIENT_STATUS_CODE = PATS_IN_HOSPITAL.PATIENT_CONDITION) PATIENT_STATUS_NAME,
       PATS_IN_HOSPITAL.NURSING_CLASS,
        (SELECT NURSING_CLASS_NAME FROM NURSING_CLASS_DICT
            WHERE NURSING_CLASS_CODE = PATS_IN_HOSPITAL.NURSING_CLASS  ) NURSING_CLASS_NAME,
        (CASE PATS_IN_HOSPITAL.NURSING_CLASS 
            WHEN '0' THEN '255,128,255' 
            WHEN '1' THEN '255,0,0' 
            WHEN '2' THEN '0,255,0' 
            WHEN '3' THEN '255,255,255'
            WHEN '7' THEN '128,0,128'
        ELSE '255,255,255' END) NURSING_CLASS_COLOR
  FROM PATS_IN_HOSPITAL, PAT_MASTER_INDEX,
  (select patient_id,max(visit_id) visit_id,max(ADMISSION_DATE_TIME) ADMISSION_DATE_TIME from PAT_VISIT 
  where sysdate - discharge_date_time < 3 or discharge_date_time is null group by patient_id) PAT_VISIT
 WHERE PAT_MASTER_INDEX.PATIENT_ID = PAT_VISIT.PATIENT_ID and
   PATS_IN_HOSPITAL.PATIENT_ID  (+) = PAT_VISIT.PATIENT_ID and
     PATS_IN_HOSPITAL.visit_id  (+) = PAT_VISIT.visit_id and
      PAT_MASTER_INDEX.inp_no is not null
       and  PATS_IN_HOSPITAL.WARD_CODE is not null

// 功能:
       获取在院病人基本信息
   
   返回值: (必须返回如下字段)
      PATIENT_ID		: 病人标识
      VISIT_ID			: 病人本次住院标识
      INP_NO			: 住院号
      NAME			: 姓名
      SEX			: 性别
      DATE_OF_BIRTH		: 出生日期
      ADMISSION_DATE_TIME	: 入院日期时间
      WARD_CODE			: 病区代码
      DEPT_CODE			: 科室代码
      WARD_NAME			: 病区名称
      DEPT_NAME			: 科室名称
      BED_NO			: 床号
      BED_LABEL			: 床标
      DOCTOR_IN_CHARGE		: 主治医生
      DIAGNOSIS			: 主要诊断
      ALERGY_DRUGS		: 过敏药物
      PATIENT_STATUS_NAME	: 病情名称
      NURSING_CLASS_NAME	: 护理等级名称
      NURSING_CLASS_COLOR	: 护理等级颜色
      ID_NO                     : 身份证号